# Site settings
title: Yudi's Title
email: yudiko@vt.edu
description: Yudi's Personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yudiko.github.io" # the base hostname & protocol for your site
github_username:  yudiko

# Build settings
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: false